### ISSUE TITLE
Ability to define disk size of  image

### ISSUE THREAD

**Issue by cristianacarpinteiro** [inductiva/inductiva#327]
Now, the image disk size default is 10 gb, which is not enough when I'm running longer simulation. I would like to have the option to define this on the client side.

**Comment by sarmento** [comment]
This make sense, and I think this should be a feature.
But this goes back to that situation we havd talked about. Ideally, if we are *just writing every once in a while in between tons of computation*, then we may want to mount a bucket on the local filesysystem, so that we can directly write there don't have to worry about this. Remember that big local disks ARE expensive.

**Comment by begaiym-k** [comment]
I think what Cristiana means here is that we need more disk space for the docker images that we upload to the instances. Gromacs images are large, so the default size 10 GB is not enough for Gromacs executers.

**Comment by sarmento** [comment]
Got it!! So, just to make it clear: we don't need more space because we are writing to disk, is that it? @cristianacarpinteiro ?

**Comment by cristianacarpinteiro** [comment]
@sarmento I think that part of the problem is that during the simulation gromacs generates a lot of auxiliary files, but they are necessary to run the subsequent commands. This combined with the large GROMACS image makes it run out of space and the executer fails.

**Comment by sarmento** [comment]
OK! so the problem is a storage problem. I am not convinced that the solution is just increasing the image size -- which I can see that helps but it does not seem to be the only / best solution. Ideally, all those file would be written (and later read from) a bucket so that we don't have to make the size of the image depend on the process we are running. Talk with @hpenedones to see what is the best course of action in the short, mid and long term, but clearly increasing the size of the image is just a short term fixe.
