### ISSUE TITLE
[Heat sink scenario] Add support for a arbitrary heat sink shape

### ISSUE THREAD

**Issue by fabiocruz** [inductiva/inductiva#333]
Apart from the parametrization suggested in #332, it would be great to support arbitrary mesh files as representations of heat sinks. Finding the interfaces (between the heater and the sink and between the sink and the air) would be trickier in this case.

**Comment by sarmento** [comment]
I think you should prioritize this wrt to the parametrization of the shape of the skin you mentioned in #332. Parametrization is only important when we want to perform search / optimization, but how you parametrize shapes should be part of a different discussion that is wider than just this specific scenario. In the future we want to have 3DShape class that can be extended to object that can be parametric, and these will be passed to the scenario. So, for now, assume that you are going to receive a cad file, and later we will pass a 3DShape object. But definetly start with the ability to load different object instead of parametrizing the sink in this scenario.

**Comment by IvanPombo** [comment]
Closing since we aren't going to develop this scenario further.
