### ISSUE TITLE
[Example data and Assets]: location in the package, naming, etc

### ISSUE THREAD

**Issue by sarmento** [inductiva/inductiva#604]
It's good that we are adding some data artifacts to the code base to help running examples in an easier way.
However, we really need to think about where we place them in the structure.
For example, this:
```
inductiva.examples.load_insulin()
```
is not a good location since it suggest that we can use this on any domain.
The previous version:
```
inductiva.molecules.examples.load_insulin()
```
was better since, at the very least, it would define the context in which this example works.
But, I also don't think this is still the right way of doing it. 

a) Do we need to place it under examples package (weird)
b) Naming is very confusing too: what does this method return?

Let's discuss this.

**Comment by cristianacarpinteiro** [comment]
I agree with you. But since there may be some functions that are necessary for all downloads, maybe we can do: 

`inductiva.examples.molecules.load_insulin()`  and inside the examples module we have the functions necessary to fetch all the examples. 
Regarding the name I was trying to follow  something like [scikit-learn](https://scikit-learn.org/stable/datasets/toy_dataset.html). But maybe I can change it to` download_insulin_protein()` to be more specific to what the function actually does.

**Comment by sarmento** [comment]
No! No! No!  :)
Why are we making things overly complicated?
People: I can't always be fighting this war, ok?
