### ISSUE TITLE
[ProteinSolvation]: First example in docs needs visualization compatible with terminal

### ISSUE THREAD

**Issue by sarmento** [inductiva/inductiva#628]
I was able to run the gromacs example (osx, python 3.8.8, client 0.3.2) but the interactive visualization does not work on my terminal:

```
INFO:absl:File downloaded to /Users/lsarmento/swash/1ZNI.pdb
INFO:absl:Task ID: 1695127750922324383
INFO:absl:Creating input archive...
INFO:absl:Input archive created.
INFO:absl:Input archive size: 29.49 KiB
INFO:absl:Uploading input...
INFO:absl:Input archive uploaded.
INFO:absl:Task request submitted.
INFO:absl:Waiting for resources...
INFO:absl:The task is being executed remotely.
INFO:absl:Task completed successfully.
INFO:absl:Task completed successfully.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 349k/349k [00:00<00:00, 1.27MiB/s]
Traceback (most recent call last):
  File "test3.py", line 20, in <module>
    output.render_interactive()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/inductiva/utils/optional_deps.py", line 48, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/inductiva/molecules/protein_solvation/post_processing.py", line 77, in render_interactive
    self.enable_vizualization()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/inductiva/utils/optional_deps.py", line 48, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/inductiva/molecules/protein_solvation/post_processing.py", line 154, in enable_vizualization
    raise ImportError("IPython is not available. Visualization is "
ImportError: IPython is not available. Visualization is only available in a python notebook.
```

In general the first example of each scenario should work with the least possible number of dependencies. There should be methods that provide barebones visualization options (e.g. a simple jpeg) that users can safely run first with almost 100% assurance. More advanced examples can have more exotic visualization options, but the user should always be able to use the simplest possible options to start with.

**Comment by IvanPombo** [comment]
The first example of the ProteinSolvation scenario should work, since it is not doing any rendering. However, what you want will take a few weeks of extra work and may be only possible when we start moving the post-processing to the backend. Why? Because the current open-source and commercially available packages we have tested do not run within terminal or VSCode (for example). @cristianacarpinteiro is addressing this issue in a recently created issue #616.

With all this in mind, I would suggest that the WindTunnel is the scenario example that we present on the main README.md. However, notice that we will also need to install the extra dependencies...
