### ISSUE TITLE
Tasks should automatically to the user launched machines 

### ISSUE THREAD

**Issue by begaiym-k** [inductiva/inductiva#664]
I have been testing launching machines and running my scenarios in there. At the moment for the simulation to run my machines I need to pass machine_group param to the simulate method. However, in case I restart the script or reload the window I will have to retrieve the machine group object and pass it to the simulate method again. 
I suggest automating this for the user. If I for example, have machines running in the background my tasks should automatically go there even without me explicitly passing machine_group parameter.

**Comment by IvanPombo** [comment]
I like this suggestion! However, there is more to this than it seems... For example, users may forget easily that they have left machines up, since there is no reference to them in their scripts anymore. Could you elaborate on this proposal a bit more - with ideas on the implementation side - so we can more easily discuss the details.

**Comment by hpenedones** [comment]
Right, this is a good question, and I like that you are thinking of ways of removing user pain. But indeed it's a bit unclear what the best option is, because:
- what happens if the user has more than one machine group running? where should the task go to?
- what happens if the user really wanted to send some things to the default pool? does this mean it's now impossible to do it, until the machine group is terminated? Maybe that's a fair "rule", but it's not easy to estimate if this is "intuitive behavior" for the user...
At the moment, I think we should keep this kind of things "explicit choices". It's always easy to implement a default hidden choice, but until we know what is really intuitive, I would keep them explicit.

But maybe you have some idea in mind?

**Comment by sarmento** [comment]
I think the users needs to be explicit about where to go.
What we can have is a method that allows us to select the "most recent" group, so that if the user does something like

```
machine_group=admin.most_recent_machine_group()
```

it's always the last group the user started.

If 

```
machine_group=None
```

then is should go to de default pool.

**Comment by IvanPombo** [comment]
What do you guys think of having this suggestion as an environment variable, like with the `inductiva.api_key`, `inductiva.working_dir`, etc... Obviously, users would still need to fetch the machine and decide which one they have, but then, they wouldn't need to pass it to the simulate - which could be remove from all of them. In this way, we clean up a bit the simulator part and still offer the user the explicit choice. Obviously, @sarmento suggestion still makes sense, to make things easier.

Example for creating a machine group:
```python
import inductiva

# Create a machine group
machines = inductiva.resources.MachineGroup(...)

inductiva.machine_group = machines

machines.start()

scenario = inductiva.fluids.WindTunnel()
scenario.simulate()
```

Example for using an already started machine group:
```python
import inductiva

# Create a machine group
machines =  inductiva.resources.most_recent_machine_group()
inductiva.machine_group = machines

scenario = inductiva.fluids.WindTunnel()
scenario.simulate()
```

Example for default - exactly as we currently have it:
```python
import inductiva

scenario = inductiva.fluids.WindTunnel()
scenario.simulate()
```

**Comment by IvanPombo** [comment]
> For the API key I think it makes sense to have it as a global variable because it's reasonable to assume that a single user is submitting tasks to that script. For the machines, I don't think it makes sense to define it as a global variable. I think it's very reasonable to assume that the user may want to have two different machine groups and submit different kinds of simulations to each, no?

But I would say that he would use two different scripts for that, and not in a single script. However, I think we can wait and receive user feedback for this move!
